version: "2"
services:
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-persistence:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  mysql:
    image: mysql:latest
    volumes:
      - "eris-mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eris
      MYSQL_DATABASE: eris
      MYSQL_USER: eris
      MYSQL_PASSWORD: eris
  bot:
    build: .
    depends_on:
      - mysql
      - redis
    environment: 
      DB_HOST: mysql
      DB_USERNAME: eris
      DB_PASSWORD: eris
      DB_DATABASE: eris
      REDIS_HOST: redis
    env_file:
      - .env
volumes:
  redis-persistence:
    driver: local
  eris-mysql:
    driver: local
