version: "2"
services:
  redis:
    image: bitnami/redis:latest
    volumes:
      - redis-persistence:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  mysql:
    image: mysql:latest
    volumes:
      - "eris-mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eris
      MYSQL_DATABASE: eris
      MYSQL_USER: eris
      MYSQL_PASSWORD: eris
  bot:
    image: https://docker.pkg.github.com/evocation-discord/eris/eris:stable
    depends_on:
      - mysql
      - redis
    environment: 
      DB_HOST: eris
      DB_USERNAME: eris
      DB_PASSWORD: eris
      DB_DATABASE: eris
volumes:
  redis-persistence:
    driver: local
  eris-mysql:
    driver: local
