version: "3"
services:
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-persistence:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  redis-persistence:
