name: Docker CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Build and deploy package to GitHub Package Registry"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install Dependencies and Build Code
        run: |
          npm install
          npm run build
      - name: Publish to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: evocation-discord/eris/eris
          username: ${{ github.actor }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tags: 'latest,stable'
          registry: docker.pkg.github.com